# Configuration for voxelize experiment
exp_name = "voxelize"

data_dir = "/main/rajrup/Dropbox/Project/GsplatStream/gsplat/data/Actor01/Sequence1/"
scene_id = 0
resolution = 2 # Resolution of the actorshq dataset (1, 2, 4)
data_factor = 1  # Downsample factor for the dataset. ActorsHQ dataset is already downsampled with correct intrinsics.
test_every = 8  # Every N images is a test image
# patch_size = null  # Random crop size for training (experimental)
# global_scale = 1.0  # Global scale factor for scene size
# normalize_world_space = true  # Normalize the world space
# camera_model = "pinhole"  # Camera model: pinhole, ortho, fisheye

# Freeze parameters configuration
freeze_splats = true
[freeze_params]
means = true
quats = false
scales = true
opacities = false
sh0 = false
shN = false

# [strategy]  # Strategy for GS densification
# refine_start_iter = 500  # Iteration to start refinement
# refine_stop_iter = 15000  # Iteration to stop refinement
# reset_every = 3000  # Iteration to reset the strategy
# refine_every = 100  # Iteration interval for refinement
# prune_opa = 0.1  # Prune gaussians with opacity below this threshold (higher = more aggressive pruning)
# grow_grad2d = 0.0005  # Threshold for growing gaussians (higher = more conservative)
# prune_scale3d = 0.05  # Prune gaussians with 3D scale above this threshold (lower = more aggressive pruning)
# verbose = true  # Print verbose information about densification
